### ISSUE TITLE
patient data 

### ISSUE THREAD

**Issue by msherafatian** [zhiyhu/scFT-paper#4]
Hi
Thank you for sharing your data and code in regard to your published paper. I am a bit confused over patient information provided in GEO, the paper and your codes. Could you please clarify these issues for me?
- In the paper it is mentioned that the cohort consists of 5 ovarian and 5 endometrial patients in addition to 5 benign patients. GEO accessions are "GSE132149" for cancer patients and "GSE139079" for benign samples. Is that correct?
- In the "GSE132149" I found information in regard to "11511", "11519", "11528" , "11529" , "11543", "11545", "11553" samples and in  "GSE139079" there are 6 samples named b1 to b6. Are b1 to b6 correspond to benign patients? 
- Could you provide a dataset of all reads as it is imported in your codes? for example:
"scFT-paper_rds/20191016data_integration_all_sceset.rds"

**Comment by zhiyhu** [comment]
Hi Masih,

Thanks for your interest in our work.

Since the questions are closely related to the manuscript and the data and I saw that you have emailed your inquiry to the corresponding authors, we will address this via email.

I will close this thread in 3 days.

**Comment by zhiyhu** [comment]
Hi Masih,

Thanks for your interest in our work.

Since the questions are closely related to the manuscript and the data and I saw that you have emailed your inquiry to the corresponding authors, we will address this via email.

I will close this thread in 3 days.
